# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

caching_pairwise_compare_u <- function(blocks, names) {
    .Call(`_meshgp_caching_pairwise_compare_u`, blocks, names)
}

caching_pairwise_compare_uc <- function(blocks, names, ct_obs) {
    .Call(`_meshgp_caching_pairwise_compare_uc`, blocks, names, ct_obs)
}

caching_pairwise_compare_uci <- function(coords, indexing, names, ct_obs) {
    .Call(`_meshgp_caching_pairwise_compare_uci`, coords, indexing, names, ct_obs)
}

check_gibbs_groups <- function(block_groups, parents, children, block_names, blocks, maxit = 10L) {
    .Call(`_meshgp_check_gibbs_groups`, block_groups, parents, children, block_names, blocks, maxit)
}

Kpp <- function(x1, x2, theta, same = FALSE) {
    .Call(`_meshgp_Kpp`, x1, x2, theta, same)
}

Kppc <- function(coords, ind1, ind2, theta, same = FALSE) {
    .Call(`_meshgp_Kppc`, coords, ind1, ind2, theta, same)
}

Kpp_mp <- function(x1, x2, theta, same = FALSE) {
    .Call(`_meshgp_Kpp_mp`, x1, x2, theta, same)
}

xKpp <- function(x1, x2, params) {
    .Call(`_meshgp_xKpp`, x1, x2, params)
}

KppG <- function(coords, ind1, ind2, theta, same = FALSE) {
    .Call(`_meshgp_KppG`, coords, ind1, ind2, theta, same)
}

Kpp_choice <- function(coords, ind1, ind2, theta, same = FALSE) {
    .Call(`_meshgp_Kpp_choice`, coords, ind1, ind2, theta, same)
}

csplit <- function(x_orig) {
    .Call(`_meshgp_csplit`, x_orig)
}

ms_seq <- function(coords, ell) {
    .Call(`_meshgp_ms_seq`, coords, ell)
}

find_not_nan <- function(infield, filtering) {
    .Call(`_meshgp_find_not_nan`, infield, filtering)
}

hex_to_dec <- function(hex_value) {
    .Call(`_meshgp_hex_to_dec`, hex_value)
}

hex_to_dec_vec <- function(vec_hex) {
    .Call(`_meshgp_hex_to_dec_vec`, vec_hex)
}

noseqdup <- function(x, has_changed, maxc, na = -1L, pred = 2L) {
    .Call(`_meshgp_noseqdup`, x, has_changed, maxc, na, pred)
}

mesh_gibbs_groups <- function(layers_descr, Mv, rfc) {
    .Call(`_meshgp_mesh_gibbs_groups`, layers_descr, Mv, rfc)
}

turbocolthreshold <- function(col1, thresholds) {
    .Call(`_meshgp_turbocolthreshold`, col1, thresholds)
}

kthresholds <- function(x, k) {
    .Call(`_meshgp_kthresholds`, x, k)
}

part_axis_parallel <- function(coords, Mv, n_threads) {
    .Call(`_meshgp_part_axis_parallel`, coords, Mv, n_threads)
}

mesh_graph_cpp <- function(layers_descr, Mv, rfc) {
    .Call(`_meshgp_mesh_graph_cpp`, layers_descr, Mv, rfc)
}

mvn <- function(n, mu, sigma) {
    .Call(`_meshgp_mvn`, n, mu, sigma)
}

list_mean <- function(x) {
    .Call(`_meshgp_list_mean`, x)
}

qmeshgp_mcmc <- function(y, X, coords, blocking, parents, children, layer_names, layer_gibbs_group, indexing, phi1_prior, phi2_prior, start_w, theta, beta, tausq, sigmasq, mcmcsd, recover, mcmc_keep = 100L, mcmc_burn = 100L, mcmc_thin = 1L, num_threads = 1L, adapting = FALSE, cache = FALSE, cache_gibbs = FALSE, rfc = FALSE, verbose = FALSE, debug = FALSE, printall = FALSE, saving = TRUE, sample_beta = TRUE, sample_tausq = TRUE, sample_sigmasq = TRUE, sample_theta = TRUE, sample_w = TRUE) {
    .Call(`_meshgp_qmeshgp_mcmc`, y, X, coords, blocking, parents, children, layer_names, layer_gibbs_group, indexing, phi1_prior, phi2_prior, start_w, theta, beta, tausq, sigmasq, mcmcsd, recover, mcmc_keep, mcmc_burn, mcmc_thin, num_threads, adapting, cache, cache_gibbs, rfc, verbose, debug, printall, saving, sample_beta, sample_tausq, sample_sigmasq, sample_theta, sample_w)
}

qmeshgp_dry <- function(y, X, coords, blocking, parents, children, layer_names, layer_gibbs_group, indexing, start_w, theta, beta, tausq, sigmasq, mcmcsd, mcmc_keep = 100L, mcmc_burn = 100L, mcmc_thin = 1L, num_threads = 1L, adapting = FALSE, cache = FALSE, cache_gibbs = FALSE, rfc = FALSE, verbose = FALSE, debug = FALSE, printall = FALSE, sample_beta = TRUE, sample_tausq = TRUE, sample_sigmasq = TRUE, sample_theta = TRUE, sample_w = TRUE) {
    .Call(`_meshgp_qmeshgp_dry`, y, X, coords, blocking, parents, children, layer_names, layer_gibbs_group, indexing, start_w, theta, beta, tausq, sigmasq, mcmcsd, mcmc_keep, mcmc_burn, mcmc_thin, num_threads, adapting, cache, cache_gibbs, rfc, verbose, debug, printall, sample_beta, sample_tausq, sample_sigmasq, sample_theta, sample_w)
}

