# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

caching_pairwise_compare_u <- function(blocks, names) {
    .Call(`_meshgp_caching_pairwise_compare_u`, blocks, names)
}

caching_pairwise_compare_uc <- function(blocks, names, ct_obs) {
    .Call(`_meshgp_caching_pairwise_compare_uc`, blocks, names, ct_obs)
}

caching_pairwise_compare_uci <- function(coords, indexing, names, ct_obs) {
    .Call(`_meshgp_caching_pairwise_compare_uci`, coords, indexing, names, ct_obs)
}

check_gibbs_groups <- function(block_groups, parents, children, block_names, blocks, maxit = 10L) {
    .Call(`_meshgp_check_gibbs_groups`, block_groups, parents, children, block_names, blocks, maxit)
}

find_not_nan <- function(infield, filtering) {
    .Call(`_meshgp_find_not_nan`, infield, filtering)
}

hex_to_dec <- function(hex_value) {
    .Call(`_meshgp_hex_to_dec`, hex_value)
}

hex_to_dec_vec <- function(vec_hex) {
    .Call(`_meshgp_hex_to_dec_vec`, vec_hex)
}

list_mean <- function(x) {
    .Call(`_meshgp_list_mean`, x)
}

list_qtile <- function(x, q) {
    .Call(`_meshgp_list_qtile`, x, q)
}

noseqdup <- function(x, has_changed, maxc, na = -1L, pred = 2L) {
    .Call(`_meshgp_noseqdup`, x, has_changed, maxc, na, pred)
}

mesh_gibbs_groups <- function(layers_descr, Mv, rfc) {
    .Call(`_meshgp_mesh_gibbs_groups`, layers_descr, Mv, rfc)
}

turbocolthreshold <- function(col1, thresholds) {
    .Call(`_meshgp_turbocolthreshold`, col1, thresholds)
}

kthresholds <- function(x, k) {
    .Call(`_meshgp_kthresholds`, x, k)
}

part_axis_parallel <- function(coords, Mv, n_threads) {
    .Call(`_meshgp_part_axis_parallel`, coords, Mv, n_threads)
}

part_axis_parallel_fixed <- function(coords, thresholds, n_threads) {
    .Call(`_meshgp_part_axis_parallel_fixed`, coords, thresholds, n_threads)
}

mesh_graph_cpp <- function(layers_descr, Mv, rfc) {
    .Call(`_meshgp_mesh_graph_cpp`, layers_descr, Mv, rfc)
}

mvn <- function(n, mu, sigma) {
    .Call(`_meshgp_mvn`, n, mu, sigma)
}

xCovHUV_base <- function(h, u, v, params, q, dim) {
    .Call(`_meshgp_xCovHUV_base`, h, u, v, params, q, dim)
}

xCovHUV <- function(coords, ind1, ind2, cparams, Dmat, same = FALSE) {
    .Call(`_meshgp_xCovHUV`, coords, ind1, ind2, cparams, Dmat, same)
}

qmeshgp_svc_mcmc <- function(y, X, Z, coords, blocking, parents, children, layer_names, layer_gibbs_group, indexing, set_unif_bounds_in, start_w, theta, beta, tausq, sigmasq, mcmcsd, recover, mcmc_keep = 100L, mcmc_burn = 100L, mcmc_thin = 1L, num_threads = 1L, adapting = FALSE, cache = FALSE, cache_gibbs = FALSE, rfc = FALSE, verbose = FALSE, debug = FALSE, printall = FALSE, saving = TRUE, sample_beta = TRUE, sample_tausq = TRUE, sample_sigmasq = TRUE, sample_theta = TRUE, sample_w = TRUE) {
    .Call(`_meshgp_qmeshgp_svc_mcmc`, y, X, Z, coords, blocking, parents, children, layer_names, layer_gibbs_group, indexing, set_unif_bounds_in, start_w, theta, beta, tausq, sigmasq, mcmcsd, recover, mcmc_keep, mcmc_burn, mcmc_thin, num_threads, adapting, cache, cache_gibbs, rfc, verbose, debug, printall, saving, sample_beta, sample_tausq, sample_sigmasq, sample_theta, sample_w)
}

