# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

caching_pairwise_compare_uci <- function(coords, indexing, names, ct_obs) {
    .Call(`_meshgp_caching_pairwise_compare_uci`, coords, indexing, names, ct_obs)
}

hex_to_dec <- function(hex_value) {
    .Call(`_meshgp_hex_to_dec`, hex_value)
}

hex_to_dec_vec <- function(vec_hex) {
    .Call(`_meshgp_hex_to_dec_vec`, vec_hex)
}

list_mean <- function(x) {
    .Call(`_meshgp_list_mean`, x)
}

list_qtile <- function(x, q) {
    .Call(`_meshgp_list_qtile`, x, q)
}

mesh_gibbs_groups <- function(layers_descr, Mv, rfc) {
    .Call(`_meshgp_mesh_gibbs_groups`, layers_descr, Mv, rfc)
}

kthresholdscp <- function(x, k) {
    .Call(`_meshgp_kthresholdscp`, x, k)
}

part_axis_parallel <- function(coords, Mv, n_threads, verbose = FALSE) {
    .Call(`_meshgp_part_axis_parallel`, coords, Mv, n_threads, verbose)
}

part_axis_parallel_fixed <- function(coords, thresholds, n_threads) {
    .Call(`_meshgp_part_axis_parallel_fixed`, coords, thresholds, n_threads)
}

mesh_graph_cpp <- function(layers_descr, Mv, rfc, verbose = TRUE) {
    .Call(`_meshgp_mesh_graph_cpp`, layers_descr, Mv, rfc, verbose)
}

mvn <- function(n, mu, sigma) {
    .Call(`_meshgp_mvn`, n, mu, sigma)
}

vec_to_symmat <- function(x) {
    .Call(`_meshgp_vec_to_symmat`, x)
}

xCovHUV_base <- function(h, u, v, params, q, dim) {
    .Call(`_meshgp_xCovHUV_base`, h, u, v, params, q, dim)
}

xCovHUV <- function(coords, ind1, ind2, cparams, Dmat, same = FALSE) {
    .Call(`_meshgp_xCovHUV`, coords, ind1, ind2, cparams, Dmat, same)
}

eigenchol <- function(A) {
    .Call(`_meshgp_eigenchol`, A)
}

qmgp_Cinv <- function(coords, blocking, parents, block_names, indexing, theta, Dmat, num_threads = 1L, cache = FALSE, verbose = FALSE, debug = FALSE) {
    .Call(`_meshgp_qmgp_Cinv`, coords, blocking, parents, block_names, indexing, theta, Dmat, num_threads, cache, verbose, debug)
}

qmgp_sampler <- function(coords, blocking, parents, block_names, indexing, theta, Dmat, num_threads = 1L, cache = FALSE, verbose = FALSE, debug = FALSE) {
    .Call(`_meshgp_qmgp_sampler`, coords, blocking, parents, block_names, indexing, theta, Dmat, num_threads, cache, verbose, debug)
}

qmeshgp_mv_mcmc <- function(y, X, coords, mv_id, blocking, parents, children, layer_names, layer_gibbs_group, indexing, set_unif_bounds_in, beta_Vi, tausq_ab, start_w, theta, beta, tausq, mcmcsd, mcmc_keep = 100L, mcmc_burn = 100L, mcmc_thin = 1L, num_threads = 1L, adapting = FALSE, cache = FALSE, cache_gibbs = FALSE, verbose = FALSE, debug = FALSE, printall = FALSE, sample_beta = TRUE, sample_tausq = TRUE, sample_theta = TRUE, sample_w = TRUE) {
    .Call(`_meshgp_qmeshgp_mv_mcmc`, y, X, coords, mv_id, blocking, parents, children, layer_names, layer_gibbs_group, indexing, set_unif_bounds_in, beta_Vi, tausq_ab, start_w, theta, beta, tausq, mcmcsd, mcmc_keep, mcmc_burn, mcmc_thin, num_threads, adapting, cache, cache_gibbs, verbose, debug, printall, sample_beta, sample_tausq, sample_theta, sample_w)
}

qmeshgp_svc_mcmc <- function(y, X, Z, coords, blocking, parents, children, layer_names, layer_gibbs_group, indexing, set_unif_bounds_in, beta_Vi, sigmasq_ab, tausq_ab, start_w, theta, beta, tausq, sigmasq, mcmcsd, recover, mcmc_keep = 100L, mcmc_burn = 100L, mcmc_thin = 1L, num_threads = 1L, adapting = FALSE, cache = FALSE, cache_gibbs = FALSE, rfc = FALSE, verbose = FALSE, debug = FALSE, printall = FALSE, saving = TRUE, sample_beta = TRUE, sample_tausq = TRUE, sample_sigmasq = TRUE, sample_theta = TRUE, sample_w = TRUE) {
    .Call(`_meshgp_qmeshgp_svc_mcmc`, y, X, Z, coords, blocking, parents, children, layer_names, layer_gibbs_group, indexing, set_unif_bounds_in, beta_Vi, sigmasq_ab, tausq_ab, start_w, theta, beta, tausq, sigmasq, mcmcsd, recover, mcmc_keep, mcmc_burn, mcmc_thin, num_threads, adapting, cache, cache_gibbs, rfc, verbose, debug, printall, saving, sample_beta, sample_tausq, sample_sigmasq, sample_theta, sample_w)
}

mvCovAG20107 <- function(coords, qv_block, ind1, ind2, ai1, ai2, phi_i, thetamv, Dmat, same = FALSE) {
    .Call(`_meshgp_mvCovAG20107`, coords, qv_block, ind1, ind2, ai1, ai2, phi_i, thetamv, Dmat, same)
}

